# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Marc Minor Makes (Almost) Anything
email: mminor@gsd.harvard.edu
description: MIT MAS.863 Marc Minor Class Blog
baseurl: '/classes/863.16/section.Harvard/people/Minor' # the subpath of your site, e.g. /blog
url: 'fab.cba.mit.edu/' # the base hostname & protocol for your site
twitter_username: marcminor
github_username: marcminor

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging

# Pagination
paginate: 12

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  john:
    name: Marc Minor
    display_name: Marc Minor
    bio: I (Marc) am a student at Harvard's Graduate School of Design, focusing on design technology. I also run marketing at a metal 3D printing start-up. And I'm a dad...2017 is going to be tiring.
    gravatar: https://secure.gravatar.com/avatar/fabf6531a89d701aff7c6819bae675ef
    email: mminor@gsd.harvard.edu
    web: http://marcminor.com
    twitter: marcminor
    github: marcminor