# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: East
email: your-email@domain.com
description: Minimal and Clean Blog Jekyll Theme
baseurl: '' # the subpath of your site, e.g. /blog
url: 'https://east-jekyll.aerobatic.io' # the base hostname & protocol for your site
twitter_username: aspirethemes
github_username: aspirethemes

# Build settings
markdown: kramdown
permalink: pretty
include:
  - _pages
exclude:
  - Gemfile
  - Gemfile.lock
gems:
  - jekyll-paginate
  - jekyll/tagging

# Pagination
paginate: 12

# Tags
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty

authors:
  john:
    name: John Adam
    display_name: John Adam
    bio: Adam have over 5 years of experience as a web writer, and also a photographer.
    gravatar: http://east.aspirethemes.com/content/images/2016/01/smiles-man.jpg
    email: john@aspirethemes.com
    web: http://aspirethemes.com
    twitter: aspirethemes
    github: aspirethemes